export const countries = [
    "Nigeria",
    "United States",
    "United Kingdom",
    "Canada",
    "France",
    "Australia",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Ghana",
    "Togo",
    "Benin Republic",
    "Cameroon",
    "Dubai",
    "Netherlands"
  ];
  